### ISSUE TITLE
fails when building with r10e

### ISSUE THREAD

**Issue by DanAlbert** [pelya/libiconv-libicu-android#3]
``` bash
$ PATH=/path/to/android-ndk-r10e:$PATH ./build.sh
...
LD_LIBRARY_PATH=/work/src/Boost-for-Android/libiconv-libicu-android/armeabi/icu/source/cross/lib:/work/src/Boost-for-Android/libiconv-libicu-android/armeabi/icu/source/cross/stubdata:/work/src/Boost-for-Android/
libiconv-libicu-android/armeabi/icu/source/cross/tools/ctestfw:$LD_LIBRARY_PATH /work/src/Boost-for-Android/libiconv-libicu-android/armeabi/icu/source/cross/bin/icupkg -d ./out/build/icudt52l --list -x \* ./in/i
cudt52l.dat -o out/tmp/icudata.lst
/bin/sh: /work/src/Boost-for-Android/libiconv-libicu-android/armeabi/icu/source/cross/bin/icupkg: No such file or directory
...
```

**Comment by pelya** [comment]
Builds okay on my setup. Could you please try to change NCPU to 1 inside
build.sh? Do you have GCC and G++ installed on your host system?

**Comment by DanAlbert** [comment]
I had done that, wasn't any better. It seemed to be the first thing that came up, so possibly a missing dependency?

Yes, have GCC and G++ (gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4)

**Comment by pelya** [comment]
Try to install all packages listed here:
https://github.com/pelya/commandergenius/blob/sdl_android/project/jni/application/xserver/readme.txt
It's compilation instructions for a different Android app, but they set up
the same environment as on my work PC.

**Comment by multiplemonomials** [comment]
For anyone else who has the same error, I figured out what's causing this problem.  In order to build libicu, the build script first builds it for the host system architecture, then uses the tools that were built the first time around (including `icupkg`) to compile it for Android.  This error message means that the compile for the host system failed.  It won't ever retry the compile because it sees that the `<your arch>/icu/source/cross` directory exists.  So, delete that folder, rerun the build script, and keep a close eye for the error that is causing the host build to fail.
